#!/usr/bin/perl -w

my $test = 30;
use strict;
 print    "Hello world\n";

print ("one ". "two ". "three ". "four\n");

#here we print two arguments 
print ("one ". "two\n"). "three ". "four\n\a";
#here lists
#
print ("Here is a list  containing strings, (This one) numbers (3.6) and variables : $test \n");

print<<EOF;

Here is the Document using here-document way , the thing is that we can print anything using << 
and it will be printed until it find the word next to the << so ..


EOF

##NOW desigualdades 
#
#
print "five is more than six?",     6 < 5, "\n";
