#!/usr/bin/perl -Tw

use strict;
my $soa;

sub cleanline {
   my $line=shift;
   chomp($$line);
   $$line =~ s/;.*//;
   $$line =~ s/(\s+)/ /g;
}

while (<>) {
   cleanline(\$_);
   if (/IN\s+SOA/) {
     if (/\(/) {
       $soa.=$_;
       until ($soa =~ /\)/) {
         $soa .= (<>);
         cleanline(\$soa);
       }
     }
   }
}

$soa =~ /IN SOA [\S]+ [\S]+[^\d]*([\d]*).*/;
print $1,"\n";
