#!/bin/bash 

hits() {
for x in {1..5};
do
	ssh="app1v-log.tp.prd.lax.gnmedia.net"
        echo  "`ssh $ssh  'tail -1000 app${x}v-mal.ao.prd.lax.gnmedia.net/myanimelist.net_access_log | awk '{print $1}'  | egrep 46.251.88.37|5.164.176.104 | wc -l'`"

done
}
hits

