#!/bin/bash 

#NUM=$RANDOM
#RANGO=20
#echo $((NUM %= 20))
#echo $((NUM%20+10))
		RANGE=10
                number=$((RANDOM % RANGE))
                echo "$number ?"

		read ab
		if [ $ab == 1 ]
		then
		RANGE=10
                number=$((RANDOM % RANGE + number))
		echo $number
		fi
		

