#!/bin/bash 

#get info from netapp 
GET_NETAPP=`ssh admin@netapp1.gnmedia.net 'volume show -aggregate netapp1_03_aggr1' | grep netapp | awk '{print $2}'`


for x in $GET_NETAPP
do
        ssh xcat.gnmedia.net 'rnetapp netapp1_nfs exports list $x | grep -v vol'
done

