#!/bin/bash
DATE=`date +"%d%m%Y"`
DIR="/run/media/rcarreon/*"
DIRI="/run/media/rcarreon"
DESTDIR="/home/rcarreon/Documents/robbaks"
echo "This script will backup either automagically or manually media extraible devices to a custom dir $DESTDIR"
sleep 2
echo "Automatic backup or manual ? a/m"
read ans 
if [ $ans  == "a" ];then 
	if [ "$(ls -A $DIR)" ];then
  	   echo "These are the dirs inside $DIR "
	   echo "`ls $DIR`"
	   sleep 5
	   echo "backing up to $DESTDIR"
	   #for x in `ls $DIR`
#		do
#		   mkdir -p $DESTDIR/robback_$DATE/$x
		   rsync -varupEth --progress $DIR $DESTDIR/robback_$DATE
		   echo "Success!"
#	  	   exit 0
#		done
	else
	    echo "$DIR is Empty nothing to backup"
	    exit 13
	fi
	#rsync -varupEth --progress /run/media/rcarreon/robc_sd/DCIM /home/rcarreon/Documents/robbaks/robcelback_18092016
else
	if [ $ans == "m" ];then 
		if [ "$(ls -A $DIRI)" ];then
           		echo "These are the dirs inside $DIRI"
		        echo "`ls  $DIRI`"
           		echo "Which one are you backing up ? "
	   		read backup
			echo "This are the dirs inside $DIRI/$backup"
			echo "`ls $DIRI/$backup`"
			echo "You want to backup all of them or just one ? ( type * for all ) "
#			echo "Which one you want to backup ?"
			read backup2
	   		echo "Backing up $backup/$backup2"
			mkdir -p $DESTDIR/robback_$DATE/$backup
    	   		rsync -varupEth --progress $DIRI/$backup/$backup2 $DESTDIR/robback_$DATE/$backup	
			echo "Backup successfully"
           		exit 0
   	 	else 
	   		echo "$DIR is empty nothing to backup"
		fi 
	fi
fi
