#!/bin/bash
solver=`/usr/bin/which  bc_solver`
echo "Inodes or volume increase? i/v"
read tipo
if [[ $tipo == "i" ]]; then
	echo "Gie the current inodes"
	read ino
	echo "Give max inodes capacity"
	read rino
	tinod=$($solver $ino /.70)
	echo "New value for inodes should be $tinod to reach to 70%"
	echo "Means that it has increased `$solver  $tinod - $rino` "
fi 
if [[ $tipo == "v" ]]; then 
	
		echo "Give Current usage"
		read usage
		echo "Give Total volume capacity"
		read Total
		TA2R=`/usr/bin/bc_solver $usage /.70`
		#TA2R=`echo "$usage/.80" | /usr/bin/bc `
		A2I=`/usr/bin/bc_solver $TA2R - $Total`
#		echo "size to reach"
		#A2I= `echo "$TA2R - $Total" | /usr/bin/bc`
		echo "You have to increase $A2I gigs to get 70%"
		echo "Use this:  sudo rnetapp <filer> volume size <volume> +$A2I"g""
	
fi 

