#!/bin/bash

#credentials for mysql
sql=`which mysql`
sql_u="noctools_r"
#sql_pass="pd0Id6vq"
sql_pass="2dxIKzSy"
#sql_host="sql1v-rt.tp.dev.lax.gnmedia.net"
sql_host_prd="vip-sqlrw-rt.tp.prd.lax.gnmedia.net"
sql_query_verts="SELECT  cfv.Name  FROM CustomFields AS cf INNER JOIN CustomFieldValues AS cfv ON cf.id = cfv.CustomField WHERE cf.Name =  'Vertical'"
sql_query_rcs="SELECT  cfv.Name  FROM CustomFields AS cf INNER JOIN CustomFieldValues AS cfv ON cf.id = cfv.CustomField WHERE cf.Name =  'Root Cause'"
TODO_verts=`$sql -u "$sql_u" -p"$sql_pass" -h "$sql_host_prd" -e "$sql_query_verts" rt3 | awk '$NR<1'`
TODO_rcs=`$sql -u "$sql_u" -p"$sql_pass" -h "$sql_host_prd" -e "$sql_query_rcs" rt3 | awk '$NR<1'`
verticals=('NULL' $TODO_verts)
rootcs=('NULL' $TODO_rcs)
printf  "Verticals\n"
for item in ${verticals[*]}
do
	printf " %s\n" $item 
done
echo "Root Causes"
for it in ${rootcs[*]}
do
	printf " %s\n" $it
done
	echo $sql_host_prd
###mysql query 
#mysql -u noctools_r -ppd0Id6vq -h sql1v-rt.tp.dev.lax.gnmedia.net -e "SELECT cfv.id, cfv.Name  FROM CustomFields AS cf INNER JOIN CustomFieldValues AS cfv ON cf.id = cfv.CustomField WHERE cf.Name =  'Vertical'" rt3

