#!/bin/perl -w 
## Esto pruba que el 6 platicador es una farsa 
for(my $x=6;$x=>2;$x--){
	print "ya quedan $x y son las " . `date +"%T"`;
	if ($x == 2){
		print "vamos por mas..!@! \n";
		$x = $x +12;
	}
}
