#!/bin/bash
AWK=`which awk`
SED=`which sed`
#if [ $# -lt 1 ]
#then 
#	echo "Usage - $0 ip address"
#	exit 1 
#else 

echo "Would  you provide a file or a site, or just a public ip ? f/s/i "
read ans 
if [ -z $ans ]
        then
                echo "You must provide an option"
elif [ $ans == f ]
then 
	echo "give me the path"
	read path
	
for line in $(cat $path)
do
	LOCATION=`curl -Ls http://iplocation.truevue.org/?ip=$line | grep -i located | $AWK '{print $5, $6, $7, $8, $9, $10, $11, $12}' | $SED 's/strong//g; s/"//g; s/<[^>]*>//g; s/Following//g'` 


#	LOCATION2=`echo -e $LOCATION | sed s/center//d`
	echo  "$LOCATION"
done 
exit 0 
#fi
	elif  [ $ans == i ] 
	then 
		echo "Give me the public IP address"
		read public
		#LOCATION2=`curl -Ls http://iplocation.truevue.org/?ip="$public" | grep -i located | $AWK '{print $5, $6, $7, $8, $9, $10, $11, $12, $13}' | $SED 's/strong//g; s/"//g; s/[^>]*>//g; s/Following//g'` 
		LOCATION2=`curl -Ls http://iplocation.truevue.org/?ip=$public | grep -i located | $AWK '{print $5, $6, $7, $8, $9, $10, $11, $12, $13}' | $SED 's/strong//g; s/"//g; s/<[^>]*>//g; s/Following//g'`
		echo "$LOCATION2"	
	
	elif  [ $ans == s ]
	then
		echo "Give the Site"
		read site 
		IP=`ping -c 1 $site  | head -n1 | $AWK '{print $3}'| $SED 's/[()]//g'` 
		LOCATION3=`curl -Ls http://iplocation.truevue.org/?ip=$IP | grep -i located | $AWK '{print $5, $6, $7, $8, $9, $10, $11, $12, $13}' | $SED 's/strong//g; s/"//g; s/<[^>]*>//g; s/Following//g'`
		echo "$LOCATION3"	
else
	echo "Option not recognized "
	exit	1
fi
exit 0 
