#!/bin/bash
#
# Script to see whether argument is positive or negative
#
if [ $# -eq 0 ]
then
echo "$0 : You must give/supply one integers"
exit 1
fi


if test $1 -gt 0
then
echo "$1 number is positive"
else
echo "$1 number is negative"
fi

####explanation####
#if number of expresions ($#) = (-eq) 0 
# echo  name of the script ($0) and then.. You must give/supply one integers"


####
#if test what we get from keyboard ($1) geater than (-gt) 0
#then echo $1 is possitive 
#else echo $1 is negative
###

