#!/bin/bash
# if no vehicle name is given
# i.e. -z $1 is defined and it is NULL
#
# if no command line arg
vehi=0
echo "Which vehicle do you preffer"
read vehi
if [ -z $vehi ] #string is  NULL and does exist
then
  rental="*** Unknown vehicle ***"
elif [ -n $vehi ] #string is not NULL and does exist
then
# otherwise make first arg as rental
  rental=$vehi
fi
## our "Database" note the quotes
case $rental in
   "car") echo "For $rental Rs.20 per k/m";;    
   "van") echo "For $rental Rs.10 per k/m";;
   "jeep") echo "For $rental Rs.5 per k/m";;
   "bicycle") echo "For $rental 20 paisa per k/m";;
   *) echo "Sorry, I can not gat a $rental for you";;
esac
