#!/bin/bash
echo "diamond"
echo "how loarge diamonds"
read dia
for (( i=1; i<=$dia; i++))
do 
	for (( j=1; j<=i; j++))
	do
	echo -n " *"
	done
	echo ""
done

for (( i=$dia; i>=1; i--))
do 
	for (( j=1; j<=i; j++ ))
	do
	echo -n " *"
	done
	echo ""
done
