#!/bin/python
import os
import subprocess
import paramiko
import sys
import datetime 
from datetime import timedelta

def pinger():
    hostname =  "google.com"
    now = datetime.datetime.now()
    print now
    response = subprocess.call(['ping', '-c', '1', '-W', '1', hostname],
                                          stdout=open('/dev/null', 'w'), stderr=open('/dev/null', 'w'))
    #response = os.system("/usr/bin/ping -c 2 " + hostname  + "> /dev/null 2>&1")
    #response =subprocess.call(['ping', '-c', '1', '-W', '1', hostname])
    #and then check the response...
    if response == 0:
        print hostname, 'is up!'
        #os.system('play --no-show-progress --null --channels 1 synth %s sine %f' % ( a, b))
    else:
        print hostname, 'is down! or Megashits network, restarting service... '
        command =  ['service', 'NetworkManager', 'restart'];
        subprocess.call(command,shell=False)

pinger()
