#!/bin/bash

while read line 
do
#	echo -e  "$line  "
CONTENT_HTTP=`curl -ILs $line | grep HTTP | grep 200 > /dev/null ; echo $?`
	echo $CONTENT_HTTP
done < "/home/rcarreon/test/webtesting/tst_text"

