#!/usr/bin/perl
$u = undef;
@all = qw< rob car bar >;
#pushing elements at the end of the array
push @all, za;
print "@all \n";
#poping last element of the array
pop @all;
print "\n @all \n";
#Now at the beggining of the array
#
unshift @all, to;
print "\n @all ";
#Now at the end 
#
$a = shift(@all);
$b = shift @all;
shift @all;
print "\n now the arrays has @all[0] \n";


my %fruit_color = (
	apple => "green",
	banana => "yellow",
	orange => "naranja",
	);
print "$fruit_color[0] \n";
