#!/usr/bin/perl

# this one  calculates circumferences 
#
$radius = 12.5;
$circum = 2 * 3.1415;
$result= $radius * $circum;
print "$result \n ";


# now with input  from keyboard 
#
$radius2 = <STDIN>;
$circum2 = 2 * 3.1415;
$result2 = $radius2 * $circum2;
print  "$result2 \n";

# Now if input is less than 0 the  result must be 0
#
$radius3 = <STDIN>;
if ( $radius3 <= 0 ) {
	$circum3 = 0;
	$result3 = $radius3 * $circum3;
	print "The result is $result3 \n"
}	else {
	$circum3 = 2 * 3.1415;
	$result3 = $radius3 * $circum3;
	print "$result3 \n ";
}

#Now multiplaying number from 2 inputs
#
print "Give me a number \n";
 $number1 = <STDIN>;
print "Give me 2nd number \n ";
 $number2 = <STDIN>;
$mult= $number1 * $number2;
print "The 2 numbers multiplied are  $mult \n";
#
#Now we need to multiply the given string with the given number
print "Give me a string to mutlipy \n";
  $string = <STDIN>;
print "Give me a number \n";
  $number3 = <STDIN>;
#yet another way to tge input
#
$string2 = $ARGV[1];
$number4 = $ARGV[2];

#$result4 = $string * $number3;
#
#here is tricky  the operand  x  takes the left operand the string $string and makes  $number3 copies of it and with . comes the concatanation
print $string x $number3 .  "\n";

print $ARGV[1] . $ARGV[2];
#
#
#End of excercises part 1 
