#!/usr/bin/perl -w
use 5.14.4;
#saying 
$what = "brontosaurus steak";
$n = 3;
$ten = 10;
say "fred ate $n $whats.\n";          # not the steaks, but the value of $whats
say "fred ate $n ${what}s.\n";        # now uses $what
say "fred ate $n $what" . "s.\n";     # another way to do it
say 'fred ate ' . $n . ' ' . $what . "s.\n"; # an especially difficult way

$ten = 20;
$ten = $ten + 10;

say  "\n $ten \n";
#--  get input from keyboard --
$line = <STDIN>;
   say $line;
#-- now with  chomp
chomp($line2 = <STDIN>);
say $line2


#$n = 0;
$fred[0] = "yabba";
$fred[1] = "dabba";
$fred[2] = "doo";

say "$fred[$#fred]  \n";
#pintint number of items in array
say 'number of item in array fred is' .  @fred ;
#--lists-- arrays

@oneq=("one", "two", "three");

$oneq=("one", "two", "three");
@twoq=qw / yahoo! google excite lycos /;
say "\n @twoq  \n @oneq \n";
say "\n @twoq[1] is a search engine \n";
say "$oneq";


