#!/usr/bin/perl -w 


sub marine {
 $n +=1;
 print "Hello sailor $n\n";
}

&marine;


sub sum_of_two_values {
	$number1 + $number2;
}

$number1 = <STDIN>;
$number2 = <STDIN>;

$result = &sum_of_two_values;
print "$result \n";


#max of two numbers provided by args
#
 sub max {
         if ($_[0] > $_[1]) {
 	         $_[0];
         } else {
        	 $_[1];
         }
  }

$r = &max(10, 20);    
print "the max is $r\n"

#
#
#
sub max2 {
      my($m, $n);       # new, private variables for this block
      ($m, $n) = @_;    # give names to the parameters
      if ($m > $n) { $m } else { $n }
}
$t = &max2;
print "$t"
