#!/usr/bin/perl -w


use strict;
no warnings;
my $SERVER="xcat.gnmedia.net";
sub search_xcat{
	print	"dame el sitio\n";
	my $SITE=<STDIN>;
	if ($SITE =~ m/sherdog/){
		my $srch= `ssh $SERVER sudo nodels | grep sdc | grep prd`;
	}else{
		print "not a valid site";
	}
}

&search_xcat;



