#!/bin/bash
source $HOME/sandbox/dns_script/updateserial
TR=`echo $1 | tr [a-z] [A-Z]`
calculate_ip=$(ipcalc -cs $2)
output=$?
usage (){
	echo "Usage : $0 -record -ipaddress -hostname"
	echo "	    For NS :  $0  -record -hostname"
	exit 1 
 }
if [[ $# -eq 2 ]];then
        if [[ $TR == "NS" ]];then

                sed -i   ' /)/a\\t IN \t '$TR'\t '$2'.' revzonetemplate
        else
                echo "Not an NS record "
                usage
        fi
elif [[ $# -eq 3 ]];then

        if [[ "$output" == "0" && $TR != "NS" ]]; then
                IP=`echo $2 | cut -d . -f 4`
                printf "$IP\tIN\t$TR\t$3.\n" >> revzonetemplate
        else
                echo "Bad IP address/record or not provided correctly"
                usage
        fi
	
else 
	echo "Number of args not correct.. exiting"
	usage 
 
#echo "Not valid IP adress"
fi                
updateserial "revzonetemplate"
