#!/bin/bash
## 11/12 by rcarreon
## Solo esta funcionando para el archivo testing.net.db se puede cambiar por un argumento claro ..  casi termindo para agregar a .rev file 
source $HOME/sandbox/dns_script/updateserial
TR=$(echo $3 | tr [a-z] [A-Z] )
responsetime=10
##tabs for more easy use 
tab=$(printf "\t")
usage(){
	echo " usage; $0 -a  will add host"
	echo "	    :-flag -hostzonename -record -ipaddr|hostname"
	echo "	    : $0 -d 'hostzonename' -record this option will delete a hostzonename and its record "
	exit 1 
}
hostname=$2
## busqueda del record para la, mas que nada para la eliminacion del mismo..
rec_search(){
		thesearch=$(grep ''$hostname'\..*'$TR'' testing.net.db | uniq | awk '{print $3}')
		if [[ -z "$thesearch" ]]; then 
			echo "Record not found  search"
			exit 99 
		else 
		case $thesearch in 
			CNAME)
		 	        return 21
				;;
			A)	
				return 22
				;;
			PTR)
				return 23
				;;
			NS)	
				return 24
				;;
			MX)	
				return 25
				;;
			*)
				return 99
				;;
		esac 
	 	fi 

}
## Esta funcion no sirve .. yet 

if [ -z "$1" ];then
	echo "no valid argument"
	usage
else
	case $1 in 
		-a)
			if [ $# -lt 4 ];then
				echo "not enough arguments"
				usage
				
			fi
			case $3 in 
				ns|NS)  
					sed -i '  /)/a'$2'.	IN	'$TR'	'$4'.' testing.net.db
					;;
				mx|MX)
				printf "$2.\t\tIN\t$TR\t$responsetime\t$4.\n" >> testing.net.db
				#sed -i ' /)/a   '$2'.            IN      '$TR'  '$responsetime'   '$4'.' testing.net.db
				;;
				a|A|ptr|PTR) printf  "$2.\t\tIN\t$TR\t$4\n" >> testing.net.db
				;;
				*)
					echo "Not a valid record"
					exit 1 
				;;
			esac
			;;

		-d) if [[ -z "$TR" ]]; then
			echo "Need a record type to delete"
			usage	
		else 
			rec_search
			output=$?
			#could be with case.
			if [[ $output = "21" ]];then 
				sed -i '/^'$hostname'\.*\s.*CNAME/d' testing.net.db
				echo "CNAME record deleted"
			elif [[ $output = "22" ]];then
				sed -i '/^'$hostname'\.*\s.*A/d' testing.net.db
				echo "A record deleted"
			elif [[ $output = "23" ]];then
				sed -i '/^'$hostname'\.*\s.*PTR/d' testing.net.db
				echo "PTR record deleted"
			elif [[ $output = "24" ]];then 
				sed -i '/^'$hostname'\.*\s.*NS/d'  testing.net.db
				echo "NS record deleted"
			elif [[ $output = "25" ]];then 
				sed -i '/^'$hostname'\.*\s.*MX/d' testing.net.db
				echo "MX record deleted"
			else
				echo "Record not found  deletion"
				exit 1 
			fi 
			#sed -i '/^'$2'\.*\s.*'$TR'/d' testing.net.db
		fi
		;;
	 	 *) echo "not a valid option";usage;;
	esac
fi
		echo "Finishing "
 	        echo "Updating serial.."
		echo "Done"
#Aqui actualizamos el serial 
updateserial "testing.net.db"
exit 0

