#!/bin/bash 
updateserial (){
        get_date=$(date +%Y%m%d)
        serial=$(cat  "$1"| grep -i 'serial'| awk '{print $1}')
        serial_aux=$(echo `expr "$serial" : '\(........\)'`)
        x=$(printf $get_date"%02d")
	echo $get_date
	
if [[ $serial_aux -gt $get_date ]];then
        echo "Your serial is in the future"
        sed -i 's/'$serial'/'$x'/' $1
elif
        [[ $serial -eq $x ]];then
                x_aux=$(( x + 1 ))
                sed -i 's/'$serial'/'$x_aux'/' $1
elif    [[ $x -lt $serial ]]; then
                x_aux=$(( $serial + 1 ))
                sed -i 's/'$serial'/'$x_aux'/' $1
elif    [[ $get_date -gt $serial_aux ]];then
                sed -i 's/'$serial'/'$x'/' $1
        else
                echo "Nothing to do "
                exit 1
fi
}

